name: pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - uses: docker://pandoc/core:latest
        with:
          args: >-  # allows you to break string into multiple lines
            -t slidy
            -o index.html
            presentation.md

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages # The branch the action should deploy to.
          folder: ./ # The folder the action should deploy.